### ISSUE TITLE
Параметры подключения к брокеру

### ISSUE THREAD

**Issue by Roman1us** [andreypopov/node-red-contrib-wirenboard#1]
Приветствую!

Думаю, проще было бы использовать уже существующую ноду MQTT для настройки соединения с брокером. Из плюсов легко было бы уже использовать существующие настройки соединения с mqtt, а так же в существующей ноде доступны настройки SSL/TLS и другие параметры.

**Comment by andreypopov** [comment]
в новой версии добавлены настройки подключения к mqtt
