### ISSUE TITLE
Не загружается список каналов

### ISSUE THREAD

**Issue by squizshee** [andreypopov/node-red-contrib-wirenboard#12]
Добрый день. Собственно не загружается список каналов в список, ни в одной из нод. Реквизиты подключения к mqtt верные(в ноде mqtt-in - все работает). 
В консоли видно, что при нажатии на кнопку "обновить", запрос для получения списка выполняется успешно и в ответе есть список каналов. Ошибок в js-консоли не наблюдается.
![chrome_kbiApYa7Tw](https://github.com/andreypopov/node-red-contrib-wirenboard/assets/1832188/f1e2aaf1-b4e9-497a-971e-03217c83a5d1)

**Comment by andreypopov** [comment]
Не могу повторить, у меня работает.
Какие версии ВБ, node-red, nodejs ?

**Comment by squizshee** [comment]
WB - 6.6.0 release wb-2307
Node-RED version: v3.1.0
Node.js  version: v16.20.2

**Comment by andreypopov** [comment]
У меня нод-ред предыдущей версии, надо будет попробовать 3.1.. 

![2023-09-14_09-33-11](https://github.com/andreypopov/node-red-contrib-wirenboard/assets/1624839/8c64dfbf-bddf-4399-9f9f-07f53a5b5785)

**Comment by squizshee** [comment]
WB - чистая, добавлено пару устройств только + поднят мост mqtt между mosquitto на WB и mosquitto на резервном сервере. В MQTT Explorer - оба брокера доступны, изменения видны. В интерфейсе WB так же все хорошо. Нодой mqtt-in читаются любые топики из любого из двух брокеров. И самое странное что Node-RED отправляет запрос и получает валидный ответ с топиками, но просто в селект не выводит их и при этом ошибок вообще ни где никаких нет. Проверил логи в контейнере(docker) Node-RED - ошибок тоже нет. Node-RED - тоже в общем чистый, только поставил.

**Comment by andreypopov** [comment]
Не получается повторить... Работает на NR 3.1

**Comment by squizshee** [comment]
Перезалил прошивку на WB, поднял мост, снес все конфиги NR, переустановил node-red-contrib-wirenboard - после всех манипуляций все заработало. Не понятно что было, пока подобных проблем больше не появлялось. В итоге так и не понял в чем причина, все логи перекопал - ни каких ошибок.
