### ISSUE TITLE
old embedded jQuery module "multiple-select" v1.4.2 breaks monaco-editor in node-red 2.0.0

### ISSUE THREAD

**Issue by Steve-Mcl** [andreypopov/node-red-contrib-wirenboard#2]
** Describe issue **
Hi, much like the [issue I raised on node-red-contrib-zigbee2mqtt](https://github.com/andreypopov/node-red-contrib-zigbee2mqtt/issues/41), this repo also has an old version of "multiple-select" embedded in the `static/` folder that breaks the new monaco editor (See [here](https://discourse.nodered.org/t/node-red-2-0-0-beta-1-released/46990/84?u=steve-mcl))

The issue is (i believe) specific to multiple-select V1.4.2 and below - see this issue: wenzhixin/multiple-select#483

Could you please update to V1.5.2 as it does not cause the editor to break.

** Screens / Logs **
![image](https://user-images.githubusercontent.com/44235289/121816618-94397c00-cc74-11eb-8c0c-29ec35b50697.png)

**Comment by andreypopov** [comment]
fixed
+ node-red-contrib-wirenboard@3.5.1
