### ISSUE TITLE
Динамеческая подписка как в mqtt in узле

### ISSUE THREAD

**Issue by niklv** [andreypopov/node-red-contrib-wirenboard#5]
Узел wb-get не подписывается на топик, а только один раз его считывает

**Comment by andreypopov** [comment]
так и задумано
для подписки нужно wb-in


wb-get это получить значение по запросу, когда надо
![2022-05-30_07-35-07](https://user-images.githubusercontent.com/1624839/170917873-4b9c6a65-dd3f-4ecb-b474-7b35a44ecf0c.png)

**Comment by niklv** [comment]
Да, но через wb-in я не могу подписаться на топик который я задаю через ENV.
В mqtt-in узле есть такая возможность.
Вот мой сабфлоу обычной лампочки (пришлось делать через mqtt-in):
![изображение](https://user-images.githubusercontent.com/3831943/170999888-54275754-7acb-4fe3-b629-baeb865665cf.png)

**Comment by andreypopov** [comment]
количество отдельных подписок на mqtt ограничено, в какой-то момент начнет глючить mqtt , будет пропускать сообщения или будут приходить не те данные, с этим надо быть осторожнее

можно до subflow поставить wb-in со всеми необходимыми топиками, а в subflow обрабатывать только msg.changed , в котором будет топик

**Comment by niklv** [comment]
А какое ограничение, 10-100-1000?

**Comment by andreypopov** [comment]
у меня, где-то после 200-300 начинались проблемы, поэтому node-red-contrib-wirenboard подписывается на корневой топик /devices/# и дальше разбирает все сообщения, это быстрее выходит.

**Comment by niklv** [comment]
Всё равно как-то нехватает возможности в wb-in подставлять динамечески из переменной на какие значения вайренборда реагировать. Просто сейчас только чекбоксом можно выбрать и всё.

**Comment by niklv** [comment]
@andreypopov а что мешает сохранить корневую подписку и уже в самом узле смотреть какой топик надо считать по перменной?
